### ISSUE TITLE
As a user I want my changed comment to display the changes

### ISSUE THREAD

**Issue by Spurberino** [ITU-BDSA2024-GROUP17/Chirp#214]
Currently when a comment is changed, the revision goes through, but the first revision is displayed instead

- [ ] Make the latest version of a comment be displayed always

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the _CheepsPartial.cshtml file to display the latest revision of comments instead of the first one. This ensures that the most recent version of a comment is always shown.

You can review changes in this commit: https://github.com/mnmnk43434/ITU-BDSA2024-GROUP17-Chirp-214/commit/dd25faa4dbfa6dee6f0508f9999e22b35af08b14.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
